package findings

import (
	"sort"

	analyze "github.com/maksemen2/trustmod/internal/model"
)

var catalog = map[string]Definition{
	"TM-SEC-001": {Code: "TM-SEC-001", Title: "Reachable known vulnerability", Category: "security", Severity: analyze.SeverityCritical, VerdictImpact: analyze.VerdictBlock, Confidence: analyze.ConfidenceHigh, Description: "A vulnerability scanner reported a vulnerable symbol reachable from the current project.", Remediation: []string{"Upgrade the affected module to a fixed version.", "Run govulncheck again after the update."}},
	"TM-SEC-002": {Code: "TM-SEC-002", Title: "Known vulnerability, reachability unknown", Category: "security", Severity: analyze.SeverityHigh, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "A provider reported a module-level advisory, but reachability was not established.", Remediation: []string{"Review the advisory and upgrade if the affected package or symbol is used.", "Run govulncheck for reachability evidence."}},
	"TM-SEC-003": {Code: "TM-SEC-003", Title: "Known vulnerability, not reached by current analysis", Category: "security", Severity: analyze.SeverityLow, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceMedium, Description: "A vulnerability was reported but was not found reachable under the current analysis.", Remediation: []string{"Keep the module updated and re-run analysis when build tags change."}},
	"TM-SEC-004": {Code: "TM-SEC-004", Title: "Vulnerability scanner unavailable", Category: "security", Severity: analyze.SeverityInfo, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceHigh, Description: "govulncheck was requested but could not run.", Remediation: []string{"Install govulncheck or disable the govulncheck provider explicitly."}},
	"TM-SEC-005": {Code: "TM-SEC-005", Title: "Known malicious package indicator", Category: "security", Severity: analyze.SeverityCritical, VerdictImpact: analyze.VerdictBlock, Confidence: analyze.ConfidenceHigh, Description: "A credible upstream provider marked this package as malicious.", Remediation: []string{"Remove the module and review recent dependency changes."}},
	"TM-SEC-006": {Code: "TM-SEC-006", Title: "Checksum verification failed", Category: "security", Severity: analyze.SeverityCritical, VerdictImpact: analyze.VerdictBlock, Confidence: analyze.ConfidenceHigh, Description: "go mod verify reported that downloaded module content does not match go.sum.", Remediation: []string{"Inspect the module cache and re-download dependencies from trusted sources.", "Do not ignore checksum verification failures."}},
	"TM-SEC-007": {Code: "TM-SEC-007", Title: "go.sum missing required entry", Category: "security", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "The Go command reported a missing checksum entry.", Remediation: []string{"Run go mod tidy and commit the resulting go.sum changes."}},
	"TM-SEC-008": {Code: "TM-SEC-008", Title: "Security advisory data unavailable", Category: "security", Severity: analyze.SeverityInfo, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceHigh, Description: "A configured advisory provider did not return data.", Remediation: []string{"Retry later, use cache, or run with offline expectations."}},

	"TM-MAL-001": {Code: "TM-MAL-001", Title: "Encoded payload execution pattern", Category: "malware", Severity: analyze.SeverityCritical, VerdictImpact: analyze.VerdictBlock, Confidence: analyze.ConfidenceMedium, Description: "Local source analysis found base64 decoding near process execution, a common malware staging pattern.", Remediation: []string{"Remove the dependency or audit the decoded payload and execution path before use."}},
	"TM-MAL-002": {Code: "TM-MAL-002", Title: "Download and execute pattern", Category: "malware", Severity: analyze.SeverityCritical, VerdictImpact: analyze.VerdictBlock, Confidence: analyze.ConfidenceHigh, Description: "Local source analysis found network download, filesystem write, executable permission changes, and process execution in the same source file.", Remediation: []string{"Treat the package as untrusted until the full execution chain is manually reviewed."}},
	"TM-MAL-003": {Code: "TM-MAL-003", Title: "Sensitive data exfiltration pattern", Category: "malware", Severity: analyze.SeverityCritical, VerdictImpact: analyze.VerdictBlock, Confidence: analyze.ConfidenceMedium, Description: "Local source analysis found sensitive local data access and network client behavior in the same source file.", Remediation: []string{"Review whether secrets or host data can leave the process and avoid the dependency if this behavior is unexpected."}},
	"TM-MAL-004": {Code: "TM-MAL-004", Title: "Suspicious /etc/passwd access", Category: "malware", Severity: analyze.SeverityHigh, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceHigh, Description: "Local source analysis found direct access to /etc/passwd.", Remediation: []string{"Review why the dependency reads local account metadata and whether this is necessary for your use case."}},
	"TM-MAL-005": {Code: "TM-MAL-005", Title: "Suspicious URL literal", Category: "malware", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceLow, Description: "Local source analysis found URL literals using top-level domains often associated with disposable or suspicious infrastructure.", Remediation: []string{"Review the URL destination and whether outbound access to it is expected."}},
	"TM-MAL-006": {Code: "TM-MAL-006", Title: "Shell downloader pipeline", Category: "malware", Severity: analyze.SeverityCritical, VerdictImpact: analyze.VerdictBlock, Confidence: analyze.ConfidenceHigh, Description: "Local source analysis found a shell command that downloads remote content and pipes or executes it.", Remediation: []string{"Remove the dependency or inspect the remote script and execution path before use."}},

	"TM-ID-001": {Code: "TM-ID-001", Title: "Module path does not match repository identity", Category: "identity", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "The module path and repository metadata do not align cleanly.", Remediation: []string{"Review the canonical module path and repository ownership."}},
	"TM-ID-002": {Code: "TM-ID-002", Title: "Similar package names detected", Category: "identity", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceLow, Description: "A provider reported name similarity that may need manual review.", Remediation: []string{"Compare the module path, repository, and adoption signals before adding."}},
	"TM-ID-003": {Code: "TM-ID-003", Title: "Vanity import path could not be resolved", Category: "identity", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "A vanity module path could not be resolved by enabled providers.", Remediation: []string{"Review the vanity import host and repository manually."}},
	"TM-ID-004": {Code: "TM-ID-004", Title: "Repository not found", Category: "identity", Severity: analyze.SeverityHigh, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "The repository expected from the module path could not be found.", Remediation: []string{"Confirm the module path and repository location."}},
	"TM-ID-005": {Code: "TM-ID-005", Title: "Repository changed owner or appears moved", Category: "identity", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceLow, Description: "Repository identity signals suggest a move or ownership change.", Remediation: []string{"Review repository redirects and release history."}},
	"TM-ID-006": {Code: "TM-ID-006", Title: "Major version path mismatch", Category: "identity", Severity: analyze.SeverityHigh, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceHigh, Description: "A v2+ module version does not appear to use the expected /vN module path.", Remediation: []string{"Use the canonical major-version module path."}},
	"TM-ID-007": {Code: "TM-ID-007", Title: "Unexpected canonicalization", Category: "identity", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "The Go command canonicalized the module path or version unexpectedly.", Remediation: []string{"Review the selected module and version before accepting the change."}},
	"TM-ID-008": {Code: "TM-ID-008", Title: "Local replace directive", Category: "identity", Severity: analyze.SeverityLow, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceHigh, Description: "go.mod replaces this module with a local path.", Remediation: []string{"Confirm the local replacement is intentional and reproducible in CI."}},
	"TM-ID-009": {Code: "TM-ID-009", Title: "Remote replace directive", Category: "identity", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceHigh, Description: "go.mod replaces this module with a different remote module.", Remediation: []string{"Review the fork or replacement module before merging."}},
	"TM-ID-010": {Code: "TM-ID-010", Title: "Module path uses suspicious pattern", Category: "identity", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceLow, Description: "The module path has a pattern commonly associated with typos or throwaway packages.", Remediation: []string{"Review repository identity, release history, and import path spelling."}},

	"TM-VER-001": {Code: "TM-VER-001", Title: "Selected version is retracted", Category: "versioning", Severity: analyze.SeverityHigh, VerdictImpact: analyze.VerdictBlock, Confidence: analyze.ConfidenceHigh, Description: "The selected version is retracted by the module author.", Remediation: []string{"Upgrade to a non-retracted version."}},
	"TM-VER-002": {Code: "TM-VER-002", Title: "Latest available version is retracted", Category: "versioning", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "The latest version known to the Go command is retracted.", Remediation: []string{"Pin a maintained non-retracted version or choose another module."}},
	"TM-VER-003": {Code: "TM-VER-003", Title: "Pseudo-version selected", Category: "versioning", Severity: analyze.SeverityLow, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceHigh, Description: "The selected version is a pseudo-version rather than a tagged release.", Remediation: []string{"Prefer a tagged release when possible."}},
	"TM-VER-004": {Code: "TM-VER-004", Title: "Pre-release version selected", Category: "versioning", Severity: analyze.SeverityLow, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceHigh, Description: "The selected version is a pre-release.", Remediation: []string{"Prefer a stable release unless the pre-release is intentional."}},
	"TM-VER-005": {Code: "TM-VER-005", Title: "Module is below v1", Category: "versioning", Severity: analyze.SeverityLow, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceHigh, Description: "The module has not reached v1, so its API stability expectations may differ.", Remediation: []string{"Review the changelog and pin an explicit version."}},
	"TM-VER-006": {Code: "TM-VER-006", Title: "No tagged versions found", Category: "versioning", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "No tagged versions were found by enabled providers.", Remediation: []string{"Prefer a module with tagged releases or pin a reviewed pseudo-version."}},
	"TM-VER-007": {Code: "TM-VER-007", Title: "Version deprecated according to provider", Category: "versioning", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "A provider reported this version as deprecated.", Remediation: []string{"Upgrade to the provider-recommended version."}},
	"TM-VER-008": {Code: "TM-VER-008", Title: "Upgrade introduces higher-risk findings", Category: "versioning", Severity: analyze.SeverityHigh, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "A dependency update adds findings with a higher verdict impact.", Remediation: []string{"Review the update delta and consider a smaller version step."}},
	"TM-VER-009": {Code: "TM-VER-009", Title: "Downgrade detected", Category: "versioning", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceHigh, Description: "The dependency diff downgrades a module.", Remediation: []string{"Confirm the downgrade is intentional and does not reintroduce fixed issues."}},

	"TM-MNT-001": {Code: "TM-MNT-001", Title: "Repository archived", Category: "maintenance", Severity: analyze.SeverityHigh, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceHigh, Description: "The upstream repository is archived.", Remediation: []string{"Prefer a maintained module or document why the archived module is acceptable."}},
	"TM-MNT-002": {Code: "TM-MNT-002", Title: "Repository stale", Category: "maintenance", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceMedium, Description: "The repository has not shown recent activity.", Remediation: []string{"Review issue activity, releases, and project health manually."}},
	"TM-MNT-003": {Code: "TM-MNT-003", Title: "No recent tagged release", Category: "maintenance", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceMedium, Description: "No recent tagged release was found.", Remediation: []string{"Review changelog and maintainer activity."}},
	"TM-MNT-004": {Code: "TM-MNT-004", Title: "Single-maintainer risk", Category: "maintenance", Severity: analyze.SeverityLow, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceLow, Description: "Provider metadata suggests concentrated maintenance.", Remediation: []string{"Review maintainer bus factor and release process."}},
	"TM-MNT-005": {Code: "TM-MNT-005", Title: "Low Scorecard maintained score", Category: "maintenance", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceMedium, Description: "OpenSSF Scorecard reported a low maintained score.", Remediation: []string{"Review Scorecard details and upstream maintenance signals."}},
	"TM-MNT-006": {Code: "TM-MNT-006", Title: "Default branch inactive", Category: "maintenance", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceMedium, Description: "The default branch appears inactive.", Remediation: []string{"Review repository activity and release notes."}},
	"TM-MNT-007": {Code: "TM-MNT-007", Title: "No visible release notes", Category: "maintenance", Severity: analyze.SeverityLow, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceLow, Description: "No visible release notes were found by enabled providers.", Remediation: []string{"Review tags and changelog manually."}},
	"TM-MNT-008": {Code: "TM-MNT-008", Title: "Repository metadata unavailable", Category: "maintenance", Severity: analyze.SeverityInfo, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceHigh, Description: "Repository metadata could not be fetched.", Remediation: []string{"Retry later or review the repository manually."}},

	"TM-LIC-001": {Code: "TM-LIC-001", Title: "Banned license", Category: "license", Severity: analyze.SeverityHigh, VerdictImpact: analyze.VerdictBlock, Confidence: analyze.ConfidenceHigh, Description: "The module license matches a banned policy entry.", Remediation: []string{"Choose a module with an allowed license or request a documented exception."}},
	"TM-LIC-002": {Code: "TM-LIC-002", Title: "Unknown license", Category: "license", Severity: analyze.SeverityLow, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceMedium, Description: "Enabled providers could not determine a license.", Remediation: []string{"Review upstream license files manually."}},
	"TM-LIC-003": {Code: "TM-LIC-003", Title: "Multiple licenses require review", Category: "license", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "The module appears to use multiple licenses.", Remediation: []string{"Review license obligations with your project policy."}},
	"TM-LIC-004": {Code: "TM-LIC-004", Title: "License changed in update", Category: "license", Severity: analyze.SeverityHigh, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "The dependency diff includes a license change.", Remediation: []string{"Review the new license before merging."}},
	"TM-LIC-005": {Code: "TM-LIC-005", Title: "License data unavailable", Category: "license", Severity: analyze.SeverityInfo, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceHigh, Description: "License provider data was unavailable.", Remediation: []string{"Retry with network access or review license files manually."}},

	"TM-FP-001": {Code: "TM-FP-001", Title: "Adds many transitive modules", Category: "footprint", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceHigh, Description: "The change introduces a large transitive module footprint.", Remediation: []string{"Review whether a smaller dependency can satisfy the use case."}},
	"TM-FP-002": {Code: "TM-FP-002", Title: "Adds many packages to build", Category: "footprint", Severity: analyze.SeverityLow, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceMedium, Description: "The dependency adds many packages to the build graph.", Remediation: []string{"Review dependency graph and unused imports."}},
	"TM-FP-003": {Code: "TM-FP-003", Title: "Adds cgo usage", Category: "footprint", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceHigh, Description: "The dependency introduces cgo usage.", Remediation: []string{"Review platform support and build constraints."}},
	"TM-FP-004": {Code: "TM-FP-004", Title: "Adds unsafe usage", Category: "footprint", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceHigh, Description: "The dependency introduces unsafe package usage.", Remediation: []string{"Review why unsafe is required and whether it is isolated."}},

	"TM-CAP-001": {Code: "TM-CAP-001", Title: "Process execution capability detected", Category: "capability", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "Local static analysis found process execution APIs.", Remediation: []string{"Review the call sites and ensure inputs cannot be attacker-controlled."}},
	"TM-CAP-002": {Code: "TM-CAP-002", Title: "Filesystem write capability detected", Category: "capability", Severity: analyze.SeverityLow, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceMedium, Description: "Local static analysis found filesystem write APIs.", Remediation: []string{"Review file paths, permissions, and cleanup behavior."}},
	"TM-CAP-003": {Code: "TM-CAP-003", Title: "Network capability detected", Category: "capability", Severity: analyze.SeverityLow, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceMedium, Description: "Local static analysis found networking APIs.", Remediation: []string{"Review outbound and listener behavior under your project threat model."}},
	"TM-CAP-004": {Code: "TM-CAP-004", Title: "Unsafe or cgo capability detected", Category: "capability", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "Local static analysis found unsafe or cgo usage.", Remediation: []string{"Review memory-safety-sensitive code paths manually."}},
	"TM-CAP-005": {Code: "TM-CAP-005", Title: "Environment capability detected", Category: "capability", Severity: analyze.SeverityLow, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceMedium, Description: "Local static analysis found environment variable access or mutation.", Remediation: []string{"Review secret handling and process environment assumptions."}},
	"TM-CAP-006": {Code: "TM-CAP-006", Title: "Insecure randomness capability detected", Category: "capability", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceMedium, Description: "Local static analysis found math/rand usage that may be inappropriate for security-sensitive randomness.", Remediation: []string{"Review whether the usage is security-sensitive and prefer crypto/rand for security tokens, IDs, and secrets."}},
	"TM-CAP-007": {Code: "TM-CAP-007", Title: "Plugin or syscall capability detected", Category: "capability", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceMedium, Description: "Local static analysis found plugin loading or syscall usage.", Remediation: []string{"Review platform-specific behavior and dynamic loading boundaries."}},
	"TM-CAP-008": {Code: "TM-CAP-008", Title: "init functions detected", Category: "capability", Severity: analyze.SeverityInfo, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceMedium, Description: "Local static analysis found package init functions.", Remediation: []string{"Review init side effects if the dependency is newly introduced."}},

	"TM-POL-001": {Code: "TM-POL-001", Title: "Module denied by policy", Category: "policy", Severity: analyze.SeverityHigh, VerdictImpact: analyze.VerdictBlock, Confidence: analyze.ConfidenceHigh, Description: "The module matches a deny rule in policy.", Remediation: []string{"Remove the module or update policy with a documented exception."}},
	"TM-POL-002": {Code: "TM-POL-002", Title: "Required provider unavailable under strict policy", Category: "policy", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceHigh, Description: "A provider required by policy was unavailable.", Remediation: []string{"Retry when the provider is available or relax the policy explicitly."}},
	"TM-BAS-001": {Code: "TM-BAS-001", Title: "Baseline exception expired", Category: "baseline", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceHigh, Description: "A baseline exception has expired.", Remediation: []string{"Review the finding again and renew only with a reason and expiry."}},
	"TM-GO-001":  {Code: "TM-GO-001", Title: "Go command failed", Category: "data", Severity: analyze.SeverityMedium, VerdictImpact: analyze.VerdictReview, Confidence: analyze.ConfidenceHigh, Description: "The local go command failed while collecting dependency data.", Remediation: []string{"Run the reported go command manually and fix module errors."}},
	"TM-GIT-001": {Code: "TM-GIT-001", Title: "Git diff data unavailable", Category: "data", Severity: analyze.SeverityInfo, VerdictImpact: analyze.VerdictAllow, Confidence: analyze.ConfidenceHigh, Description: "trustmod could not collect git diff data.", Remediation: []string{"Run inside a git repository or specify a valid base ref."}},
}

func Lookup(code string) (Definition, bool) {
	def, ok := catalog[code]
	return def, ok
}

func All() []Definition {
	defs := make([]Definition, 0, len(catalog))
	for code := range catalog {
		def := catalog[code]
		defs = append(defs, def)
	}
	sort.Slice(defs, func(i, j int) bool { return defs[i].Code < defs[j].Code })
	return defs
}
